// packages-new/examples/react-vite/src/demo/MyButton.tsx
import type { OdsButtonAttribute } from '@ovhcloud/ods-components/button';
import React, { PropsWithChildren } from 'react';
import { OsdsButton } from '@ovhcloud/ods-components/button/react';
import { ODS_THEME_COLOR_INTENT } from '@ovhcloud/ods-common-theming';
import { odsFilterTransientProps } from '@ovhcloud/ods-common-core';

/**
 * default custom properties values for the custom button
 */
const DEFAULT_BUTTON_PROPS: Partial<OdsButtonAttribute> = {
  inline: false,
  color: ODS_THEME_COLOR_INTENT.accent
};

/**
 * my custom button has the same properties as `ODS`.
 * it has also onClick, in order to allow the use of onCLick on this custom react component.
 */
type MyButtonProps = PropsWithChildren<OdsButtonAttribute> & { onClick: () => void };

/**
 * Custom button component base on the `ODS` one.
 * It allows to set some base pattern for your app like managing default properties.
 * We recommend not to overuse with this kind of wrapper.
 * It is made here only the example.
 */
const MyButton: React.FC<MyButtonProps> = ({ children, ...props }) => {
  return <OsdsButton {...odsFilterTransientProps({ ...DEFAULT_BUTTON_PROPS, ...props })}>{children}</OsdsButton>
};

export default MyButton;

// packages/starters/vue-vite/src/demo/MyButton.vue
<script lang="ts">
export default {}
</script>

<script setup lang="ts">
import type { OdsButtonAttribute } from '@ovhcloud/ods-components/button';
import { OsdsButton } from '@ovhcloud/ods-components/button/vue';
import { ODS_THEME_COLOR_INTENT } from '@ovhcloud/ods-common-theming';

/**
 * default custom properties values for the custom button
 */
const DEFAULT_BUTTON_PROPS: Partial<OdsButtonAttribute> = {
  inline: false,
  color: ODS_THEME_COLOR_INTENT.accent
};

const props = withDefaults(defineProps<{id?: string}>(), { id: undefined });
</script>


<!--
/**
* Custom button component base on the `ODS` one.
* It allows to set some base pattern for your app like managing default properties.
* We recommend not to overuse with this kind of wrapper.
* It is made here only the example.
*/
-->
<template>
  <OsdsButton v-bind="{...DEFAULT_BUTTON_PROPS, ...props}" :id="id"><slot></slot></OsdsButton>
</template>

<style scoped>

</style>
